#!/bin/sh

# Create broken links and loop links that are needed by tests but that confuse
# make dist

set -ue

(
	cd mbox
	ln -s does-not-exist broken.mbox
)

(
	cd maildir
	ln -s does-not-exist broken
	ln -s loop loop

	cd broken1
	ln -s does-not-exist cur
	ln -s does-not-exist new
	ln -s does-not-exist tmp

	cd ../loop1
	ln -s . subcur
)
